### ISSUE TITLE
Reverse document lines command doesn't work if number of lines is NOT divisible by 2

### ISSUE THREAD

**Issue by JamiKettunen** [ChristianAlexander/flip#3]
Trying to reverse some input lines via the `Reverse document lines` command while the line count **is not divisible by 2** (e.g. 3, 5 or 7) causes nothing to happen.

I assume something somewhere should check if the `lines_count != 1` instead of `lines_count % 2 == 0` or similar?

Using the `Reverse selected lines` command always seems to works though.

**Comment by ChristianAlexander** [comment]
@JamiKettunen, thank you for the detailed bug report! I pushed a fix in version `0.0.4`, which has been submitted to Microsoft for publishing.
