### ISSUE TITLE
No "Reverse selected lines" option.

### ISSUE THREAD

**Issue by MaverickMartyn** [ChristianAlexander/flip#6]
![image](https://github.com/ChristianAlexander/flip/assets/2946618/20efd3d8-c4b7-4771-8dbf-b3fe3d2d4735)
What it says on the tin.
The option to reverse only the selected lines, does not show up.

**Comment by ChristianAlexander** [comment]
@MaverickMartyn, thanks for the report. I just tested the extension in the latest stable version of VS Code and was able to get both commands to show.

The `Reverse selected lines` option only shows up when the editor has a selection. Is it possible the cursor wasn't selecting anything when this partial screenshot was taken?

https://github.com/ChristianAlexander/flip/blob/1228e5064b7928bc525c83dd350ca2816d111205/package.json#L36-L43

If this is still an issue, I'll take a look. In that case, please share the version of VS Code as well as any other contextual information that could help reproduce the issue.

**Comment by MaverickMartyn** [comment]
@ChristianAlexander I just stumbled upon the old unread notification for this. Sorry that I missed it.
I'm pretty sure I had a handful of lines selected at the time, but I can no longer reproduce the problem regardless.
I'll just close this issue. :)
