### ISSUE TITLE
Add "Flip" to command title

### ISSUE THREAD

**Issue by maikthomas** [ChristianAlexander/flip#7]
Lots of VSCode extensions prefix their command names with the package name.
Also it makes it easier to see available commands. After installing this package the first thing I look for is "Flip" but saw no results.

**Comment by maikthomas** [comment]
Added a PR in case you're happy with the idea

**Comment by ChristianAlexander** [comment]
This is a great catch! I think most extensions do this prefixing through the `contributes.commands.category` property, so I'll ship an update with my own PR. 

Thank you for your contribution!

**Comment by maikthomas** [comment]
Ah, even better, thanks for sharing !
